### ISSUE TITLE
TypeError with improperly defined overrides

### ISSUE THREAD

**Issue by metal0** [Dragory/Knub#11]
![image](https://user-images.githubusercontent.com/9076708/130108644-74b99d9d-52cc-4b76-bc51-7ea603f49391.png)

Code that caused the error:
```yaml
  [...]
    overrides:
    - any:
        role: "1234"
        level: '>=10'
      config:
  [...]
```
